/**
 * Static store data — all 28 BBSM locations.
 *
 * Hardcoded so the Store Finder and Store Picker work without a network
 * connection. When the backend is accessible (production), these can be
 * replaced with live API data.
 */
import { Store } from '@/types';

export const STATIC_STORES: Store[] = [
  // ── Kathmandu Valley (Bagmati) ──────────────────────────────────────────
  {
    id: 'store-maharajgunj',
    name: 'BBSM Maharajgunj',
    address: 'Maharajgunj, Kathmandu 44600',
    province: 'Bagmati',
    phone: '01-4721927',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.7346,
    lng: 85.3320,
    manager_name: 'Ramesh Shrestha',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-tripureshwor',
    name: 'BBSM Tripureshwor',
    address: 'Tripureshwor, Kathmandu 44600',
    province: 'Bagmati',
    phone: '01-4243007',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.6981,
    lng: 85.3092,
    manager_name: 'Sanjay Maharjan',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-lazimpat',
    name: 'BBSM Lazimpat',
    address: 'Lazimpat, Kathmandu 44600',
    province: 'Bagmati',
    phone: '01-4415928',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.7245,
    lng: 85.3236,
    manager_name: 'Priya Tamang',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-jhamsikhel',
    name: 'BBSM Jhamsikhel',
    address: 'Jhamsikhel, Lalitpur 44700',
    province: 'Bagmati',
    phone: '01-5522374',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.6726,
    lng: 85.3177,
    manager_name: 'Binod Rai',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-naxal',
    name: 'BBSM Naxal',
    address: 'Naxal, Kathmandu 44600',
    province: 'Bagmati',
    phone: '01-4413026',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.7156,
    lng: 85.3316,
    manager_name: 'Anita Gurung',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-koteshwor',
    name: 'BBSM Koteshwor',
    address: 'Koteshwor, Kathmandu 44600',
    province: 'Bagmati',
    phone: '01-4603018',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.6862,
    lng: 85.3518,
    manager_name: 'Dev Kumar Shrestha',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-bhaktapur',
    name: 'BBSM Bhaktapur',
    address: 'Suryabinayak, Bhaktapur 44800',
    province: 'Bagmati',
    phone: '01-6610192',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.6710,
    lng: 85.4298,
    manager_name: 'Mohan Karmacharya',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-pulchowk',
    name: 'BBSM Pulchowk',
    address: 'Pulchowk, Lalitpur 44700',
    province: 'Bagmati',
    phone: '01-5523012',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.6761,
    lng: 85.3169,
    manager_name: 'Sunita Panta',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-chabahil',
    name: 'BBSM Chabahil',
    address: 'Chabahil, Kathmandu 44600',
    province: 'Bagmati',
    phone: '01-4480127',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.7190,
    lng: 85.3502,
    manager_name: 'Prabin Lama',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-baneshwor',
    name: 'BBSM New Baneshwor',
    address: 'New Baneshwor, Kathmandu 44600',
    province: 'Bagmati',
    phone: '01-4782019',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.6942,
    lng: 85.3421,
    manager_name: 'Rekha Bista',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-kalanki',
    name: 'BBSM Kalanki',
    address: 'Kalanki, Kathmandu 44600',
    province: 'Bagmati',
    phone: '01-4271084',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.6947,
    lng: 85.2843,
    manager_name: 'Santosh Adhikari',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-boudha',
    name: 'BBSM Boudha',
    address: 'Boudha, Kathmandu 44600',
    province: 'Bagmati',
    phone: '01-4914073',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.7207,
    lng: 85.3621,
    manager_name: 'Dawa Sherpa',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-budhanilkantha',
    name: 'BBSM Budhanilkantha',
    address: 'Budhanilkantha, Kathmandu 44600',
    province: 'Bagmati',
    phone: '01-4379241',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.7835,
    lng: 85.3667,
    manager_name: 'Kamala Rai',
    is_active: true,
    created_at: '',
    updated_at: '',
  },

  // ── Outside Valley ──────────────────────────────────────────────────────
  {
    id: 'store-pokhara',
    name: 'BBSM Pokhara',
    address: 'Newroad, Pokhara 33700',
    province: 'Gandaki',
    phone: '061-533029',
    hours: '7:00 AM – 9:00 PM',
    lat: 28.2096,
    lng: 83.9856,
    manager_name: 'Anup Gurung',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-hetauda',
    name: 'BBSM Hetauda',
    address: 'Hetauda-6, Makwanpur 44107',
    province: 'Bagmati',
    phone: '057-524301',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.4285,
    lng: 85.0321,
    manager_name: 'Sujan Ghimire',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-banepa',
    name: 'BBSM Banepa',
    address: 'Banepa Bazaar, Kavrepalanchok 45209',
    province: 'Bagmati',
    phone: '011-663041',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.6314,
    lng: 85.5204,
    manager_name: 'Nirmala Thapa',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-butwal',
    name: 'BBSM Butwal',
    address: 'Traffic Chowk, Butwal 32907',
    province: 'Lumbini',
    phone: '071-546038',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.7006,
    lng: 83.4480,
    manager_name: 'Ramila Chaudhary',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-bhairahawa',
    name: 'BBSM Bhairahawa',
    address: 'Bank Road, Siddharthanagar 32900',
    province: 'Lumbini',
    phone: '071-520714',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.5046,
    lng: 83.4561,
    manager_name: 'Saroj Tharu',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-biratnagar',
    name: 'BBSM Biratnagar',
    address: 'Mahendra Path, Biratnagar 56613',
    province: 'Koshi',
    phone: '021-527304',
    hours: '7:00 AM – 9:00 PM',
    lat: 26.4525,
    lng: 87.2718,
    manager_name: 'Suresh Limbu',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-dharan',
    name: 'BBSM Dharan',
    address: 'BP Chowk, Dharan 56700',
    province: 'Koshi',
    phone: '025-521073',
    hours: '7:00 AM – 9:00 PM',
    lat: 26.8065,
    lng: 87.2841,
    manager_name: 'Mina Rai',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-itahari',
    name: 'BBSM Itahari',
    address: 'Itahari-6, Sunsari 56705',
    province: 'Koshi',
    phone: '025-587019',
    hours: '7:00 AM – 9:00 PM',
    lat: 26.6627,
    lng: 87.2730,
    manager_name: 'Bikash Karki',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-damak',
    name: 'BBSM Damak',
    address: 'Damak-6, Jhapa 57217',
    province: 'Koshi',
    phone: '023-582047',
    hours: '7:00 AM – 9:00 PM',
    lat: 26.6545,
    lng: 87.6970,
    manager_name: 'Renu Subba',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-birgunj',
    name: 'BBSM Birgunj',
    address: 'Ghantaghar, Birgunj 44300',
    province: 'Madhesh',
    phone: '051-523071',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.0104,
    lng: 84.8771,
    manager_name: 'Satish Sah',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-janakpur',
    name: 'BBSM Janakpur',
    address: 'Station Road, Janakpurdham 45600',
    province: 'Madhesh',
    phone: '041-525308',
    hours: '7:00 AM – 9:00 PM',
    lat: 26.7288,
    lng: 85.9253,
    manager_name: 'Geeta Yadav',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-ghorahi',
    name: 'BBSM Ghorahi',
    address: 'Ghorahi-11, Dang 22400',
    province: 'Lumbini',
    phone: '082-560219',
    hours: '7:00 AM – 9:00 PM',
    lat: 28.0403,
    lng: 82.4909,
    manager_name: 'Ramkrishna Chaudhary',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-nepalgunj',
    name: 'BBSM Nepalgunj',
    address: 'Surkhet Road, Nepalgunj 21900',
    province: 'Lumbini',
    phone: '081-523047',
    hours: '7:00 AM – 9:00 PM',
    lat: 28.0503,
    lng: 81.6157,
    manager_name: 'Prabha KC',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-dhangadhi',
    name: 'BBSM Dhangadhi',
    address: 'Seti Road, Dhangadhi 10900',
    province: 'Sudurpashchim',
    phone: '091-523194',
    hours: '7:00 AM – 9:00 PM',
    lat: 28.6943,
    lng: 80.5999,
    manager_name: 'Kiran Bohara',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'store-narayanghat',
    name: 'BBSM Narayanghat',
    address: 'Pulchowk, Narayanghat, Chitwan 44200',
    province: 'Bagmati',
    phone: '056-570241',
    hours: '7:00 AM – 9:00 PM',
    lat: 27.7012,
    lng: 84.4319,
    manager_name: 'Sushila Pandey',
    is_active: true,
    created_at: '',
    updated_at: '',
  },
];

export const PROVINCES = [...new Set(STATIC_STORES.map((s) => s.province))].sort(
  (a, b) => {
    if (a === 'Bagmati') return -1;
    if (b === 'Bagmati') return 1;
    return a.localeCompare(b);
  }
);
